### ISSUE TITLE
Question regarding the early convolution

### ISSUE THREAD

**Issue by IcarusWizard** [younggyoseo/MWM#6]
Hi @younggyoseo,

Thank you for providing the code for your amazing work.

I have a question regarding the early convolution layers. I noticed that you are using three convolution layers with a kernel size of 4 and a stride of 2, resulting in a patch size of 8. However, as I understand it, using a kernel size of 4 might cause information to leak from adjacent patches, which could negatively affect the MAE training.

What are your thoughts on this? Do you think this might be a concern?

https://github.com/younggyoseo/MWM/blob/8394788bf4dcdc94c8b8ad1afb6ee36741716620/mwm/common/mae.py#L122-L135

**Comment by younggyoseo** [comment]
Hi, please check this part of the paper, that says we had to use high masking ratio to prevent such a failure case. In our follow-up paper ([MV-MWM](https://arxiv.org/abs/2302.02408)), we used even higher masking ratio of 90% 
<img width="735" alt="Screenshot 2024-07-13 at 9 02 22 AM" src="https://github.com/user-attachments/assets/25c260b3-b0ee-4f42-9e91-b65cfb598d2b">

**Comment by IcarusWizard** [comment]
ah, thanks for pointing out. I missed this part.
